/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceType = IDL.Variant({
  'flexBanner' : IDL.Null,
  'digitalPrinting' : IDL.Null,
  'tShirtPrinting' : IDL.Null,
  'stickerPrinting' : IDL.Null,
});
export const Quote = IDL.Record({
  'id' : IDL.Nat,
  'service' : ServiceType,
  'name' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
  'mobile' : IDL.Text,
});

export const idlService = IDL.Service({
  'getQuoteById' : IDL.Func([IDL.Nat], [Quote], ['query']),
  'getQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
  'getQuotesByMobile' : IDL.Func([IDL.Text], [IDL.Vec(Quote)], ['query']),
  'getQuotesByService' : IDL.Func([ServiceType], [IDL.Vec(Quote)], ['query']),
  'submitQuote' : IDL.Func(
      [IDL.Text, IDL.Text, ServiceType, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceType = IDL.Variant({
    'flexBanner' : IDL.Null,
    'digitalPrinting' : IDL.Null,
    'tShirtPrinting' : IDL.Null,
    'stickerPrinting' : IDL.Null,
  });
  const Quote = IDL.Record({
    'id' : IDL.Nat,
    'service' : ServiceType,
    'name' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
    'mobile' : IDL.Text,
  });
  
  return IDL.Service({
    'getQuoteById' : IDL.Func([IDL.Nat], [Quote], ['query']),
    'getQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
    'getQuotesByMobile' : IDL.Func([IDL.Text], [IDL.Vec(Quote)], ['query']),
    'getQuotesByService' : IDL.Func([ServiceType], [IDL.Vec(Quote)], ['query']),
    'submitQuote' : IDL.Func(
        [IDL.Text, IDL.Text, ServiceType, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };