/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'visitCount' : IDL.Nat,
  'name' : IDL.Text,
  'firstVisit' : IDL.Int,
  'lastVisit' : IDL.Int,
  'mobile' : IDL.Text,
});
export const Photo = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'blob' : ExternalBlob,
  'timestamp' : IDL.Int,
});
export const ServiceType = IDL.Variant({
  'flexBanner' : IDL.Null,
  'digitalPrinting' : IDL.Null,
  'tShirtPrinting' : IDL.Null,
  'stickerPrinting' : IDL.Null,
});
export const QuoteStatus = IDL.Variant({
  'new' : IDL.Null,
  'replied' : IDL.Null,
});
export const Quote = IDL.Record({
  'id' : IDL.Nat,
  'service' : ServiceType,
  'status' : QuoteStatus,
  'name' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
  'mobile' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
});
export const SiteSettings = IDL.Record({
  'tagline' : IDL.Text,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'siteName' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addPhoto' : IDL.Func([ExternalBlob, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'deletePhoto' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteReview' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCustomerByMobile' : IDL.Func([IDL.Text], [Customer], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
  'getQuoteById' : IDL.Func([IDL.Nat], [Quote], ['query']),
  'getQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
  'getQuotesByMobile' : IDL.Func([IDL.Text], [IDL.Vec(Quote)], ['query']),
  'getQuotesByService' : IDL.Func([ServiceType], [IDL.Vec(Quote)], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'registerOrLoginCustomer' : IDL.Func([IDL.Text, IDL.Text], [Customer], []),
  'submitQuote' : IDL.Func(
      [IDL.Text, IDL.Text, ServiceType, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'updatePhotoTitle' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateQuoteStatus' : IDL.Func([IDL.Nat, QuoteStatus], [IDL.Bool], []),
  'updateSiteSettings' : IDL.Func([SiteSettings], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'visitCount' : IDL.Nat,
    'name' : IDL.Text,
    'firstVisit' : IDL.Int,
    'lastVisit' : IDL.Int,
    'mobile' : IDL.Text,
  });
  const Photo = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'blob' : ExternalBlob,
    'timestamp' : IDL.Int,
  });
  const ServiceType = IDL.Variant({
    'flexBanner' : IDL.Null,
    'digitalPrinting' : IDL.Null,
    'tShirtPrinting' : IDL.Null,
    'stickerPrinting' : IDL.Null,
  });
  const QuoteStatus = IDL.Variant({ 'new' : IDL.Null, 'replied' : IDL.Null });
  const Quote = IDL.Record({
    'id' : IDL.Nat,
    'service' : ServiceType,
    'status' : QuoteStatus,
    'name' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat,
  });
  const SiteSettings = IDL.Record({
    'tagline' : IDL.Text,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'siteName' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addPhoto' : IDL.Func([ExternalBlob, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'deletePhoto' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteReview' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCustomerByMobile' : IDL.Func([IDL.Text], [Customer], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
    'getQuoteById' : IDL.Func([IDL.Nat], [Quote], ['query']),
    'getQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
    'getQuotesByMobile' : IDL.Func([IDL.Text], [IDL.Vec(Quote)], ['query']),
    'getQuotesByService' : IDL.Func([ServiceType], [IDL.Vec(Quote)], ['query']),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'registerOrLoginCustomer' : IDL.Func([IDL.Text, IDL.Text], [Customer], []),
    'submitQuote' : IDL.Func(
        [IDL.Text, IDL.Text, ServiceType, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'updatePhotoTitle' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateQuoteStatus' : IDL.Func([IDL.Nat, QuoteStatus], [IDL.Bool], []),
    'updateSiteSettings' : IDL.Func([SiteSettings], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };