/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Quote {
    id: bigint;
    service: ServiceType;
    name: string;
    timestamp: bigint;
    details: string;
    mobile: string;
}
export enum ServiceType {
    flexBanner = "flexBanner",
    digitalPrinting = "digitalPrinting",
    tShirtPrinting = "tShirtPrinting",
    stickerPrinting = "stickerPrinting"
}
export interface backendInterface {
    getQuoteById(id: bigint): Promise<Quote>;
    getQuotes(): Promise<Array<Quote>>;
    getQuotesByMobile(mobile: string): Promise<Array<Quote>>;
    getQuotesByService(service: ServiceType): Promise<Array<Quote>>;
    submitQuote(name: string, mobile: string, service: ServiceType, details: string): Promise<bigint>;
}
import type { Quote as _Quote, ServiceType as _ServiceType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getQuoteById(arg0: bigint): Promise<Quote> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuoteById(arg0);
                return from_candid_Quote_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuoteById(arg0);
            return from_candid_Quote_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuotes(): Promise<Array<Quote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotes();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotes();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuotesByMobile(arg0: string): Promise<Array<Quote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotesByMobile(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotesByMobile(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuotesByService(arg0: ServiceType): Promise<Array<Quote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotesByService(to_candid_ServiceType_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotesByService(to_candid_ServiceType_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitQuote(arg0: string, arg1: string, arg2: ServiceType, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuote(arg0, arg1, to_candid_ServiceType_n6(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuote(arg0, arg1, to_candid_ServiceType_n6(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
}
function from_candid_Quote_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Quote): Quote {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    service: _ServiceType;
    name: string;
    timestamp: bigint;
    details: string;
    mobile: string;
}): {
    id: bigint;
    service: ServiceType;
    name: string;
    timestamp: bigint;
    details: string;
    mobile: string;
} {
    return {
        id: value.id,
        service: from_candid_ServiceType_n3(_uploadFile, _downloadFile, value.service),
        name: value.name,
        timestamp: value.timestamp,
        details: value.details,
        mobile: value.mobile
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flexBanner: null;
} | {
    digitalPrinting: null;
} | {
    tShirtPrinting: null;
} | {
    stickerPrinting: null;
}): ServiceType {
    return "flexBanner" in value ? ServiceType.flexBanner : "digitalPrinting" in value ? ServiceType.digitalPrinting : "tShirtPrinting" in value ? ServiceType.tShirtPrinting : "stickerPrinting" in value ? ServiceType.stickerPrinting : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Quote>): Array<Quote> {
    return value.map((x)=>from_candid_Quote_n1(_uploadFile, _downloadFile, x));
}
function to_candid_ServiceType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    flexBanner: null;
} | {
    digitalPrinting: null;
} | {
    tShirtPrinting: null;
} | {
    stickerPrinting: null;
} {
    return value == ServiceType.flexBanner ? {
        flexBanner: null
    } : value == ServiceType.digitalPrinting ? {
        digitalPrinting: null
    } : value == ServiceType.tShirtPrinting ? {
        tShirtPrinting: null
    } : value == ServiceType.stickerPrinting ? {
        stickerPrinting: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
